// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace PUBGGameplayTags
{
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Gameplay_AbilityInputBlocked);



	// 입력 태그
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Move);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Turn);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Jump);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_FreeView);

	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Crouch);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Prone);

	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Walk);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Sprint);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Interact);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_FPS);

	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Active_EquipmentMain);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Active_EquipmentMain2);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Active_EquipmentSub);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Active_EquipmentEtc);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Active_EquipmentThrow);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Active_UnequipmentWeapon);

	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Primary);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Secondary);

	// 상태
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_StateTransform);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Stand);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Crouch);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Prone);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Jump);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Sprint);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Walk);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_UseEquipItem);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_AimOffset_MainGun);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_AimOffset_SubGun);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_AimOffset_Throw);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Aiming);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Aim_Scope);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Aim_ADS);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_FreeFalling);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_UmbrellaOpened);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Drink);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Shot);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Interact);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_EquipItem);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_UnequipItem);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Weapon_Switching);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Attack);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_FPS);

	// Ability

	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_ActivationGroup);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_IsDead);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Behavior_SurvivesDeath);

	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_StateTransform);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Stand);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Crouch);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Prone);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Jump);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Sprint_Check);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Sprint_Active);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Walk);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Death);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Block_Move);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Block_AbilityGameOnly);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Interact_Active);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Interact_Object);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActiveEquipment);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_UnActiveEquipment);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_SwapActiveEquipment);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_1);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_2);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Attack_3);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_AimDownSightMode);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ScopeMode);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_FPS);

	// Weapon
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Suppressor);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_NotFlash);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_1xScope);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_4xScope);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_8xScope);


	// Gameplay Event
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_StateTransform_Timer);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_StateTransform_Start);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_StateTransform_End);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Block_Move);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Block_AbilityGameOnly);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Interact);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Stand);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_ActiveEquipment_Swap);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Input_Pressed);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Trace);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Death);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Montage_Begin);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Montage_Tick);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Montage_End);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Montage_Play);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_AimDownSightMode);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_ScopeMode);


	// Cheat
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_GodMode);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cheat_UnlimitedHealth);

	// Movement

	// Message
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Interaction_Notice);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Interaction_Progress);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_Interaction_Detect);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message_AdditionalValue);

	// SetByCaller
	PUBG_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_BaseDamage);
	PUBG_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_BaseHealth);
	PUBG_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_IncomingDamage);
	PUBG_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_IncomingHealth);
	PUBG_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_IncomingERHealth);
	PUBG_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_IncomingStamina);
	PUBG_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_MoveSpeed);
	PUBG_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_MoveSpeedPercent);
	PUBG_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_AttackSpeedPercent);
	PUBG_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_HeadResistancePercent);
	PUBG_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_BodyResistancePercent);
	PUBG_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_EWeaponClassType);
	
	PUBG_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_AdditionalMaxCapacityWeight);
	
	PUBG_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_ExtraClipSize);
	PUBG_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_ReplaceClipTimePercent);
	PUBG_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_VerticalRecoilPercent);
	PUBG_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_HorizontalRecoilPercent);
	PUBG_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_AimingtimePercent);
	PUBG_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_HipfireAccuracyPercent);
	PUBG_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_AimedShootingAccuracyPercent);
	PUBG_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_FirstShotRecoilPercent);


	// Variable
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Variable_Item_CurrentDurability);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Variable_Item_MaxinumDurability);


	// GameplayCue
	/*
	PUBG_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Weapon_Attack);
	PUBG_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Weapon_Skill);
	PUBG_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Weapon_Impact);
	PUBG_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Weapon_Cast_Fireball);
	PUBG_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Weapon_Cast_Skill);
	PUBG_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Weapon_Skill_Targeting_Burst);
	PUBG_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Weapon_Skill_Targeting_Loop);
	PUBG_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Weapon_Overlay);
	PUBG_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Statue_Loop);
	PUBG_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Statue_Success);
	PUBG_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Statue_Fail);
	PUBG_API  UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Skill_Buff);
	*/

	// Cooldown
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Status_Crouch);
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Status_Prone);

	// HUD

	// Equip
	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Equip_Helmet);

	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Equip_Vest);

	PUBG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Equip_Backpack);
}